; This file was auto-generated by drush make
core = 7.x

api = 2
projects[drupal][version] = "7.x"

; Modules
projects[addressfield][version] = "1.0-beta4"

projects[ctools][version] = "1.3"

projects[commerce][version] = "1.7"

; git hub details
projects[commerce_cnp][download][type] = "git"
projects[commerce_cnp][download][url] = "https://github.com/ClickandPledge/commerce_cnp.git"
projects[commerce_cnp][download][branch] = 7.x-1.0
projects[commerce_cnp][type] = "module"
projects[commerce_cnp][version] = "1.0"

projects[commerce_coupon][version] = "1.0-beta7"

projects[commerce_coupon_fixed_amount][version] = "1.0-beta7"

projects[commerce_coupon_pct][version] = "1.0-beta7"

projects[commerce_discount][version] = "1.0-alpha1+11-dev"

projects[commerce_flat_rate][version] = "1.0-beta2"

projects[commerce_shipping][version] = "2.0"

projects[date][version] = "2.6"

projects[entity][version] = "1.1"

projects[entityreference][version] = "1.0"

projects[inline_entity_form][version] = "1.2"

projects[rules][version] = "2.3"

projects[views][version] = "3.7"

